name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Dependencies
      run: sudo apt update && sudo apt install clang llvm libelf-dev gcc-multilib
    - name: Build
      run: sudo su && cargo build --verbose
    - name: Run tests
      run: ulimit -l 100000 && cargo test --verbose && cd libbpf-helpers && cargo test --verbose
